#!/bin/bash

set -e # Exit if any command fails.

echo [DEBUG] Installing keepassxc
wget https://github.com/keepassxreboot/keepassxc/releases/download/2.7.9/KeePassXC-2.7.9-x86_64.AppImage -O ~/.local/bin/KeePassXC.AppImage
chmod +x ~/.local/bin/KeePassXC.AppImage
