#!/bin/bash

set -e # Exit if any command fails.

cd /tmp
echo [DEBUG] Installing neovim
wget -O nvim.tar.gz "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
tar -xf nvim.tar.gz
sudo install nvim-linux64/bin/nvim /usr/local/bin/nvim
# https://github.com/vscode-neovim/vscode-neovim/issues/597#issuecomment-1617282040
sudo mkdir -p /usr/local/share/nvim/
sudo cp -r nvim-linux64/share/nvim/runtime/ /usr/local/share/nvim/
rm -rf nvim-linux64 nvim.tar.gz
cd -
