#!/bin/bash

set -e # Exit if any command fails.

echo [DEBUG] Installing nvm
# https://github.com/nvm-sh/nvm
wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash
source ~/.nvm/nvm.sh
nvm install --lts --latest-npm
node -v # Check command works
npm -v # Check command works
