#!/usr/bin/env bash

file_name=lockscreen.png
file_path_spanish=$HOME/Imágenes/$file_name
file_path_english=$HOME/Images/$file_name
if [[ -f "$file_path_spanish" ]]; then
  i3lock -i $file_path_spanish
elif [[ -f "$file_path_english" ]]; then
  i3lock -i $file_path_english
fi
