#!/bin/bash

set -e # Exit if any command fails.

echo [DEBUG] Configuring tmux dotfiles
cp ~/Software/dotfiles/dotfiles/config/tmux/.tmux.conf ~
# https://unix.stackexchange.com/a/66607
#tmux source ~/.tmux.conf
