#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

# https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
execute pushd /tmp > /dev/null
if [ ! -f awscliv2.zip ]; then
    execute sudo apt install curl;
    execute curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
fi
if [ ! -d aws ]; then
    execute unzip awscliv2.zip
fi
if command -v aws 2>&1 >/dev/null; then
    log aws-cli is already installed
else
    execute sudo ./aws/install
fi
execute popd > /dev/null
execute aws --version
