#!/usr/bin/env bash

set -e # Exit if any command fails.

# Usage
# ./aws-cdk             Install
# ./aws-cdk --dry       Dry install
# ./aws-cdk --uninstall Uninstall

dry_run="0"
uninstall="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    if [[ "$1" == "--uninstall" ]]; then
        uninstall="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

# https://docs.aws.amazon.com/cdk/v2/guide/getting-started.html
if [[ $uninstall == "1" ]]; then
    execute npm uninstall -g aws-cdk
else
    execute npm install -g aws-cdk
    execute cdk --version
fi
