#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"


## https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
case "$(get_os)" in
  arch)
    execute sudo pacman -S --needed curl unzip gnupg
    execute bash -c 'curl -fsSL https://awscli.amazonaws.com/v2/install.sh | bash'
    ;;
  *)
    echo "Unsupported OS: $(get_os)" >&2
    exit 1
    ;;
esac
execute aws --version
