#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

## https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
case $(uname) in
  Linux)
    . /etc/os-release
    case "$ID" in
      arch)
        execute sudo pacman -S --needed curl unzip gnupg
        execute bash -c 'curl -fsSL https://awscli.amazonaws.com/v2/install.sh | bash'
        ;;
      *)
        echo "Unsupported Linux distribution: $ID" >&2
        exit 1
        ;;
    esac
    ;;
  *)
    echo "Unsupported OS: $(uname -s)" >&2
    exit 1
    ;;
esac
execute aws --version
