#!/bin/bash

set -e # Exit if any command fails.

log() {
    echo "[DEBUG][bash] $@"
}

execute() {
    log "execute $@"
    "$@"
}

if [ ! -f ~/.bashrc.backup ]; then
    execute cp ~/.bashrc ~/.bashrc.backup
fi
execute cp ~/Software/dotfiles/dotfiles/config/bash/.bashrc ~
