#!/bin/bash

set -e # Exit if any command fails.

echo [DEBUG] Configuring bash dotfiles
if [ -f ~/.bashrc.backup ]; then
    echo [DEBUG] File ~/.bashrc.backup already exists
else
    echo [DEBUG] File ~/.bashrc.backup does not exist. Creating
    cp ~/.bashrc ~/.bashrc.backup
fi
cp ~/Software/dotfiles/dotfiles/config/bash/.bash* ~
