#!/bin/bash

set -e # Exit if any command fails.

execute() {
    echo "[DEBUG][bash] execute $@"
    "$@"
}

if [ ! -f ~/.bashrc.backup ]; then
    execute cp ~/.bashrc ~/.bashrc.backup
fi
execute cp ~/Software/dotfiles/dotfiles/config/bash/.bashrc ~
