#!/usr/bin/env bash

set -e # Exit if any command fails.

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"


case "$(get_os)" in
  darwin)
    # https://www.macinstruct.com/tutorials/how-to-enable-git-tab-autocomplete-on-your-mac/
    execute curl https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash -o ~/.git-completion.bash
    ;;
esac
