#!/usr/bin/env bash

# https://github.com/github/copilot-cli-for-beginners/blob/main/00-quick-start/README.md#all-platforms-npm

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"



execute npm install -g @github/copilot
