#!/usr/bin/env bash

set -e

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"


case "$(get_os)" in
  arch)
    execute sudo pacman -S keepassxc
    ;;
  debian)
    execute sudo apt install -y keepassxc
    ;;
  *)
    echo "[ERROR] Unsupported OS: $(get_os)" >&2
    exit 1
    ;;
esac
