#!/usr/bin/env bash

set -e

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"


case "$(get_os)" in
  darwin)
    execute brew install --cask meld
    ;;
  *)
    execute sudo apt install -y meld
    ;;
esac
