#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

create_dir() {
    if [ -d "$@" ]; then
        log The "$@" folder already exists
    else
        log The "$@" folder does not exists. Creating
        execute mkdir -p "$@"
    fi
}

install_from_source() {
    # https://github.com/neovim/neovim/blob/master/BUILD.md#build-prerequisites
    execute pushd /tmp > /dev/null
    execute git clone --depth 1 --branch stable https://github.com/neovim/neovim
    execute cd neovim
    execute gmake CMAKE_BUILD_TYPE=Release
    case $(uname) in
      *BSD*)
        execute sudo gmake install
        ;;
      *)
        execute sudo make install
        ;;
    esac
    execute popd > /dev/null
}

install_nerd_fonts() {
    # https://www.youtube.com/watch?v=mQdB_kHyZn8
    execute pushd /tmp > /dev/null
    if [ ! -f 3270.tar.xz ]; then
        execute wget https://github.com/ryanoasis/nerd-fonts/releases/download/v3.3.0/3270.tar.xz
    fi
    if [ ! -d $HOME/.local/share/fonts ]; then
        execute mkdir $HOME/.local/share/fonts
    fi
    execute tar -xvf 3270.tar.xz --directory $HOME/.local/share/fonts
    execute popd > /dev/null
    log Showing that the new fonts are available:
    execute fc-list | grep 3270
}

install_vim_plug() {
    # https://github.com/junegunn/vim-plug?tab=readme-ov-file#neovim
    execute sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    # To run the following command the vim_plug must be configured in the config file in ~/.config/nvim/
    execute nvim -c 'PlugInstall'
    log Some manual steps are required. Open neovim and execute \`:PlugInstall\`. Press Enter to continue when done
    execute read -p "" </dev/tty
}

run_bsd() {
    # https://github.com/neovim/neovim/blob/master/BUILD.md#freebsd
    execute sudo pkg install -y cmake gmake wget gettext curl git
    # https://github.com/BurntSushi/ripgrep?tab=readme-ov-file#installation
    execute sudo pkg install -y ripgrep # Required by telescope.
    execute sudo pkg install -y xclip # To use clipboard.
    install_from_source
    install_nerd_fonts
    install_vim_plug
}

run_linux() {
    # https://github.com/neovim/neovim/blob/master/BUILD.md#ubuntu--debian
    execute sudo apt install ninja-build gettext cmake curl build-essential
    # https://github.com/BurntSushi/ripgrep?tab=readme-ov-file#installation
    execute sudo apt install -y ripgrep # Required by telescope.
    execute sudo apt install -y xclip # To use clipboard.
    install_from_source
    install_nerd_fonts

    # TODO execute pushd /tmp > /dev/null
    # TODO if [ ! -f "nvim-linux-x86_64.tar.gz" ]; then
    # TODO     # After installation, you can delete manually the downloaded/extracted files/folders. The script don't do that to avoid repeat steps when testing.
    # TODO     execute wget https://github.com/neovim/neovim/releases/download/stable/nvim-linux-x86_64.tar.gz
    # TODO     execute tar -xf nvim-linux-x86_64.tar.gz
    # TODO fi
    # TODO execute sudo install nvim-linux-x86_64/bin/nvim /usr/local/bin/nvim
    # TODO # https://github.com/vscode-neovim/vscode-neovim/issues/597#issuecomment-1617282040
    # TODO execute sudo rm -rf /usr/local/share/nvim/
    # TODO execute sudo mkdir -p /usr/local/share/nvim/
    # TODO execute sudo cp -r nvim-linux-x86_64/share/nvim/runtime/ /usr/local/share/nvim/
    # TODO execute popd > /dev/null

    install_vim_plug
}

case $(uname) in
  *BSD*)
    run_bsd
    ;;
  *)
    run_linux
    ;;
esac
