#!/bin/bash

set -e # Exit if any command fails.

sudo apt install -y ripgrep # Required by telescope nvim extension.
cd /tmp
echo [DEBUG] Installing neovim
wget -O nvim.tar.gz "https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz"
tar -xf nvim.tar.gz
sudo install nvim-linux64/bin/nvim /usr/local/bin/nvim
# https://github.com/vscode-neovim/vscode-neovim/issues/597#issuecomment-1617282040
sudo mkdir -p /usr/local/share/nvim/
sudo cp -r nvim-linux64/share/nvim/runtime/ /usr/local/share/nvim/
rm -rf nvim-linux64 nvim.tar.gz
cd -
echo [DEBUG] Installing vim-plug
sh -c 'curl -fLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

echo [DEBUG] Configuring neovim
nvim -c 'PlugInstall'

echo "[DEBUG] Some manual steps are required"
read -p "[DEBUG] Open neovim and execute \`:PlugInstall\`. Press Enter to continue when done" </dev/tty
