#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

case "$(get_os)" in
  bsd)
    execute sudo pkg install -y node
    execute sudo pkg install -y npm
    ;;
  darwin)
    execute brew install curl
    # https://github.com/nvm-sh/nvm
    execute bash -c 'wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
    execute source $HOME/.config/nvm/nvm.sh
    execute nvm install --lts --latest-npm
    ;;
  debian)
    execute sudo apt install -y curl
    # https://github.com/nvm-sh/nvm
    execute bash -c 'wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash'
    execute source $HOME/.config/nvm/nvm.sh
    execute nvm install --lts --latest-npm
    ;;
  *)
    echo "[ERROR] Unsupported OS: $(get_os)"
    exit 1
    ;;
esac
execute node -v # Check command works
execute npm -v # Check command works
