#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

NVM_VERSION="v0.40.7"
DOWNLOAD_URL="https://raw.githubusercontent.com/nvm-sh/nvm/${NVM_VERSION}/install.sh"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

install_with_sh() {
    # https://github.com/nvm-sh/nvm/releases/
    execute bash -c "curl -fsSL ${DOWNLOAD_URL} | bash"
    execute source $HOME/.config/nvm/nvm.sh
    execute nvm install --lts --latest-npm
}

case "$(get_os)" in
    arch)
        execute sudo pacman -S --needed curl
        install_with_sh
        ;;
    bsd)
        execute sudo pkg install -y node
        execute sudo pkg install -y npm
        ;;
    darwin)
        execute brew install curl
        install_with_sh
        ;;
    debian)
        execute sudo apt install -y curl
        install_with_sh
        ;;
    *)
        echo "[ERROR] Unsupported OS: $(get_os)"
        exit 1
        ;;
esac
execute node -v # Check command works
execute npm -v # Check command works
