#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    eval "$@"
}

log Installing nvm
# https://github.com/nvm-sh/nvm
execute "wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.1/install.sh | bash"
case $(uname) in
  *BSD*)
    execute source $HOME/.config/nvm/nvm.sh
    # https://github.com/nvm-sh/nvm/issues/1552
    execute export CC=cc
    execute export CXX=c++
    ;;
  *)
    execute source $HOME/.nvm/nvm.sh
    ;;
esac
execute nvm install --lts --latest-npm
execute node -v # Check command works
execute npm -v # Check command works
