#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"


# https://pipx.pypa.io/latest/installation/
case "$(get_os)" in
  bsd)
    execute sudo pkg install -y py311-pipx
    ;;
  *)
    execute sudo apt install -y pipx
    ;;
esac

execute pipx ensurepath
