#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

# https://pipx.pypa.io/latest/installation/
case $(uname) in
  *BSD*)
    execute sudo pkg install -y py311-pipx
    ;;
  *)
    execute sudo apt install -y pipx
    ;;
esac

execute pipx ensurepath
