#!/usr/bin/env bash

set -e # Exit if any command fails.

# Usage:
#   ./runs/vim             Configure vim.
#   ./runs/vim --dry       Show what would be executed, without doing it.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

copy_dotfile "vim/.vimrc" $HOME
