#!/usr/bin/env bash

set -e # Exit if any command fails.

# Usage:
#   ./runs/vim-plug             Install.
#   ./runs/vim-plug --dry       Show what would be executed, without doing it.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/lib.sh"

install_curl() {
    case "$(get_os)" in
      darwin)
        if ! command -v curl >/dev/null 2>&1; then
            echo "[ERROR] curl is expected to be available on macOS"
            exit 1
        fi
        ;;
      bsd)
        execute sudo pkg install -y curl
        ;;
      arch)
        execute sudo pacman -S --needed curl
        ;;
      debian)
        execute sudo apt install -y curl
        ;;
      *)
        echo "[ERROR] Unsupported OS: $(get_os)"
        exit 1
        ;;
    esac
}

install_vim_plug() {
    local downloads_path="$HOME/.cache/dotfiles/downloads"
    local plug_target="${XDG_DATA_HOME:-$HOME/.local/share}/nvim/site/autoload/plug.vim"
    local cached_plug_path="$downloads_path/plug.vim"
    # https://github.com/junegunn/vim-plug?tab=readme-ov-file#neovim
    if [ -s "$cached_plug_path" ]; then
        log "Found cached $cached_plug_path, skipping download"
    else
        log "No valid cached download found at $cached_plug_path, downloading"
        mkdir -p "$downloads_path"
        execute curl -fL "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim" -o "$cached_plug_path"
    fi
    mkdir -p "$(dirname "$plug_target")"
    execute cp "$cached_plug_path" "$plug_target"
    # The following needs vim_plug to be configured in the config file in ~/.config/nvim/ (done when copying the config)
    # --headless: run without opening the UI.
    # +PlugInstall --sync: install plugins and wait for installation to finish.
    # +qa: quit Neovim afterward.
    execute nvim --headless '+PlugInstall --sync' +qa
}

copy_dotfile_dir "nvim"
install_curl
install_vim_plug
