#!/usr/bin/env bash

# Note. This script name must no be `dotfiles` or it won't be filtered in the main run script because the main project name is `dotfiles`.

set -e # Exit if any command fails.

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source "$script_dir/lib.sh"

"$script_dir/runs/git"

if [ -d ~/Software/dotfiles ]; then
    log "The ~/Software/dotfiles folder already exists. Updating"
    cd ~/Software/dotfiles
    git checkout main
    git pull origin main
    cd -
else
    log "Downloading ~/Software/dotfiles"
    git clone git@github.com:CarlosAMolina/dotfiles ~/Software/dotfiles
    if [ ! -d ~/Software/dotfiles ]; then
      echo [ERROR] The ~/Software/dotfiles has not been downloaded
      exit 1
    fi
fi
