#!/usr/bin/env bash

set -e # Exit if any command fails.

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
repo_root="$( cd "$script_dir/.." && pwd )"
dotfiles_dir="$repo_root/dotfiles"

copy_file() {
    from=$1
    to=$2
    name=$(basename $from)
    if [ -f "$to/$name" ]; then
        rm $to/$name
    fi
    cp $from $to/$name
}

backup_file() {
    # Don't call as in `copy_file()` to avoid change variables with same name.
    file_path=$1
    if [ -f "$file_path" ] && [ ! -f "$file_path.bkp" ]; then
        cp $file_path{,.bkp}
    fi
}

copy_files_to_home() {
    from_dir=$1
    pushd $from_dir > /dev/null
    files=$(find . -maxdepth 1 -mindepth 1 -type f)
    for file_ in $files; do
        backup_file $HOME/$file_
        copy_file $from_dir/$file_ $HOME
    done
    popd > /dev/null
}

copy_dir_to_config() {
    from_dir=$1
    name=$(basename $from_dir)
    rm -rf $HOME/.config/$name
    cp -r $from_dir $HOME/.config/$name
}

echo "[DEBUG] Copying bash files"
copy_files_to_home "$dotfiles_dir/bash"
echo "[DEBUG] Copying git files"
copy_files_to_home "$dotfiles_dir/git"
echo "[DEBUG] Copying tmux files"
copy_files_to_home "$dotfiles_dir/tmux"
echo "[DEBUG] Copying nvim config"
copy_dir_to_config "$dotfiles_dir/nvim"
echo "[DEBUG] Copying exclude_dirs config"
copy_dir_to_config "$dotfiles_dir/exclude_dirs"
