#!/bin/bash

set -e # Exit if any command fails.

script_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

log Start host configuration

log Creating folders
if [ -d ~/Software ]; then
  log The ~/Software folder already exists
else
  log The ~/Software folder does not exists. Start creating the folder
  execute mkdir ~/Software
fi
if [ -d ~/.local/bin ]; then
  log The ~/.local/bin folder already exists
else
  log The ~/.local/bin folder does not exists. Start creating the folder
  execute mkdir -p ~/.local/bin
fi
if [ -d ~/.ssh ]; then
  log The ~/.ssh folder already exists
else
  log The ~/.ssh folder does not exists. Start creating the folder
  execute mkdir ~/.ssh
fi

log Updating apt
execute sudo apt update

log Installing software using apt
execute sudo apt install -y build-essential # installs: make
execute sudo apt install -y curl
execute sudo apt install -y git
execute sudo apt install -y htop
execute sudo apt install -y meld
execute sudo apt install -y tmux
execute sudo apt install -y trash-cli
execute sudo apt install -y xclip
execute sudo apt install -y zip
execute sudo apt install -y keepassxc

execute ./configure/github-ssh

runs_dir=`find $script_dir/install -mindepth 1 -maxdepth 1 -executable`

for script in $runs_dir; do
    execute $script
done

execute ./configure/neovim
execute ./configure/bash
execute ./configure/git
execute ./configure/tmux

log Uninstalling unrequired packages
execute sudo apt autoremove

log "Configuration done :)"
