#!/bin/bash

set -e # Exit if any command fails.

echo [DEBUG] Updating apt
sudo apt update

echo [DEBUG] Installing software using apt
sudo apt install -y build-essential # Installs: make
sudo apt install -y curl
