#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

case $(uname) in
  *BSD*)
    execute sudo pkg install git
    ;;
  *)
    execute sudo apt install -y git
    ;;
esac
if [ ! -f ~/.ssh/id_ed25519 ]; then
    log Enter your email to create a new SSH key for GitHub:
    # https://linuxconfig.org/handling-user-input-in-bash-scripts
    execute read -p "" email
    if [[ -z "$email" ]]; then
        echo "[ERROR] Email cannot be empty"
        execute exit 1
    fi
    execute ssh-keygen -t ed25519 -N '' -C "$email" -f ~/.ssh/id_ed25519
fi
execute eval "$(ssh-agent -s)"
execute ssh-add ~/.ssh/id_ed25519
log Copy the following prasshprase and save it in yout GitHub account \(https://github.com/login, https://github.com/settings/keys\)
execute cat ~/.ssh/id_ed25519.pub
# https://stackoverflow.com/questions/35075364/pause-shell-script-until-user-presses-enter
log Press Enter to continue when the passhprase is stored
execute read -p "" </dev/tty
