#!/usr/bin/env bash

set -e # Exit if any command fails.

dry_run="0"

while [[ $# -gt 0 ]]; do
    echo "ARG: \"$1\""
    if [[ "$1" == "--dry" ]]; then
        dry_run="1"
    fi
    shift
done

log() {
    if [[ $dry_run == "1" ]]; then
        echo "[DRY_RUN] $@"
    else
        echo "[DEBUG] $@"
    fi
}

execute() {
    log "execute $@"
    if [[ $dry_run == "1" ]]; then
        return
    fi
    "$@"
}

run_bsd() {
    execute sudo pkg install git
    if [ ! -f ~/.ssh/id_ed25519 ]; then
      log Enter your email to create a new SSH key for GitHub:
      # https://linuxconfig.org/handling-user-input-in-bash-scripts
      execute read -p "" email
      if [[ -z "$email" ]]; then
        echo "[ERROR] Email cannot be empty"
        execute exit 1
      fi
      execute ssh-keygen -t ed25519 -N '' -C "$email" -f ~/.ssh/id_ed25519
    fi
    execute eval "$(ssh-agent -s)"
    execute ssh-add ~/.ssh/id_ed25519
    log Copy the following prasshprase and save it in yout GitHub account \(https://github.com/login, https://github.com/settings/keys\)
    execute cat ~/.ssh/id_ed25519.pub
    # https://stackoverflow.com/questions/35075364/pause-shell-script-until-user-presses-enter
    log Press Enter to continue when the passhprase is stored
    execute read -p "" </dev/tty
}

run_linux() {
    execute sudo apt install -y git
    # TODO use log and execute
    echo [DEBUG] Start github ssh configuration
    if [ -f ~/.ssh/id_ed25519 ]; then
      echo [DEBUG] The ~/.ssh/id_ed25519 file already exists
    else
      echo [DEBUG] The ~/.ssh/id_ed25519 file does not exists. Start creating the file
      # https://linuxconfig.org/handling-user-input-in-bash-scripts
      read -p "[DEBUG] Enter your email to create a new SSH key for GitHub: " email
      if [[ -z "$email" ]]; then
        echo "[ERROR] Email cannot be empty"
        exit 1
      fi
      ssh-keygen -t ed25519 -N '' -C "$email" -f ~/.ssh/id_ed25519
    fi
    eval "$(ssh-agent -s)"
    ssh-add ~/.ssh/id_ed25519
    # https://stackoverflow.com/questions/35075364/pause-shell-script-until-user-presses-enter
    echo "[DEBUG] Copy the following prasshprase and save it in yout GitHub account (https://github.com/login, https://github.com/settings/keys)"
    cat ~/.ssh/id_ed25519.pub
    read -p "[DEBUG] Press Enter to continue when the passhprase is stored" </dev/tty

    echo [DEBUG] Installing github cli
    # https://github.com/cli/cli/blob/trunk/docs/install_linux.md
    (type -p wget >/dev/null || (sudo apt update && sudo apt-get install wget -y)) \
    && sudo mkdir -p -m 755 /etc/apt/keyrings \
    && wget -qO- https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
    && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
    && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
    && sudo apt update \
    && sudo apt install gh -y
}

case $(uname) in
  *BSD*)
    run_bsd
    ;;
  *)
    run_linux
    ;;
esac
